import type { NavConfig } from '@/lib/navigation/schema'

export const defaultNavConfig: NavConfig = {
  primaryLinks: [
    {
      id: '0f2d2c25-2506-4a66-9d4c-0c3334b3b57f',
      href: '/',
      label: 'The Game Cabbage',
      icon: '🥬',
      sortOrder: 1,
      isVisible: true,
    },
    {
      id: 'a05c3ef5-7b27-4c48-b7f3-7ca4f99a59b1',
      href: '/history',
      label: 'The Annals',
      icon: '📜',
      sortOrder: 2,
      isVisible: true,
    },
    {
      id: '56c5a59d-e69f-4888-9adb-b5f2d81c0e1a',
      href: '/posts',
      label: 'Posts',
      icon: '💬',
      sortOrder: 3,
      isVisible: true,
    },
    {
      id: 'd2f6d2f8-8c34-4a0a-86da-4d5bd24272b4',
      href: '/player-cards',
      label: 'Player Cards',
      icon: '🃏',
      sortOrder: 4,
      isVisible: true,
    },
    {
      id: '278f98e0-4ad2-4a54-8f3e-3c8d3c2e7a21',
      href: '/players',
      label: 'Players',
      icon: '👤',
      sortOrder: 5,
      isVisible: false,
    },
    {
      id: '6f9e61a7-9f12-4989-8c7b-1c9b4fa1a3a4',
      href: '/bracket',
      label: 'Bracket Generator',
      icon: '🏆',
      sortOrder: 6,
      isVisible: true,
    },
  ],
  megaMenus: [
    {
      id: 'admin',
      label: 'Admin',
      sortOrder: 1,
      isVisible: true,
      groups: [
        {
          id: 'f1bd1f83-6258-4bcb-b7fb-49620d36d8a1',
          title: 'Game Ops',
          sortOrder: 1,
          isVisible: true,
          items: [
            {
              id: '0f76b102-29ea-4a93-b12f-1d186c0e0039',
              href: '/admin/games',
              title: 'Games',
              description: 'Manage matchups and outcomes.',
              icon: 'controller',
              tone: 'moss',
              sortOrder: 1,
              isVisible: true,
            },
            {
              id: '99b146c6-4f42-4e75-90b9-9f8b1fd7ae7b',
              href: '/admin/tags',
              title: 'Tags',
              description: 'Curate metadata and categories.',
              icon: 'tags',
              tone: 'wheat',
              sortOrder: 2,
              isVisible: true,
            },
            {
              id: '58b2437e-0939-4e39-9be0-9b4f0d04c9c7',
              href: '/admin/tournaments',
              title: 'Tournaments',
              description: 'Organize brackets and schedules.',
              icon: 'trophy',
              tone: 'sky',
              sortOrder: 3,
              isVisible: true,
            },
          ],
        },
        {
          id: 'f10c8f98-9b78-4ac2-bf6d-6849095b95b1',
          title: 'Player Ops',
          sortOrder: 2,
          isVisible: true,
          items: [
            {
              id: 'c5d537f1-9c2c-46c0-a0d8-46c246a6ad86',
              href: '/admin/players',
              title: 'Players',
              description: 'Update rosters and bios.',
              icon: 'users',
              tone: 'mint',
              sortOrder: 1,
              isVisible: true,
            },
          ],
        },
        {
          id: '8b944ed1-b3a8-43fc-98a8-010f1c7851a0',
          title: 'App Ops',
          sortOrder: 3,
          isVisible: true,
          items: [
            {
              id: 'bed4c5b4-8adf-480d-a981-cfdbd847db63',
              href: '/admin/app-configurations',
              title: 'App configurations',
              description: 'Review platform settings.',
              icon: 'guide',
              tone: 'sage',
              sortOrder: 1,
              isVisible: true,
            },
            {
              id: 'b1c8e63c-7b6a-47d0-a40f-7ca0a77c0d11',
              href: '/admin/navigation',
              title: 'Navigation builder',
              description: 'Configure the primary and mega menu layouts.',
              icon: 'scroll',
              tone: 'sky',
              sortOrder: 2,
              isVisible: true,
            },
          ],
        },
      ],
    },
  ],
}
